/** todo - rename to SchemaType */
export const enum CommitType {
  BOARD_CREATE = "BOARD_CREATE",
  BOARD_UPDATE = "BOARD_UPDATE",
  BOARD_DELETE = "BOARD_DELETE",
  LIST_CREATE = "LIST_CREATE",
  LIST_UPDATE = "LIST_UPDATE",
  LIST_DELETE = "LIST_DELETE",
  CARD_CREATE = "CARD_CREATE",
  CARD_UPDATE = "CARD_UPDATE",
  CARD_DELETE = "CARD_DELETE",
  COMMENT_CREATE = "COMMENT_CREATE",
  COMMENT_UPDATE = "COMMENT_UPDATE",
  COMMENT_DELETE = "COMMENT_DELETE",
  COMMENT = "COMMENT",
  CARD = "CARD",
}
